#!/usr/bin/env python3
"""Build the final molecular feature table for machine-learning analysis.

The script combines RDKit molecular descriptors, DFT-derived geometric and
electronic descriptors, vertical IP/EA values, and the position-specific
substituent descriptors generated by ``08a_generate_substituent_features.py``.
Fukui columns are not generated or accepted as model features.
"""

from __future__ import annotations

import argparse
import math
import re
from pathlib import Path

import numpy as np
import pandas as pd
from rdkit import Chem
from rdkit.Chem import Descriptors, rdMolDescriptors

from common import dataset_dir, ensure_dir, load_manifest, read_table, read_xyz, write_table

FLOAT = r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[Ee][-+]?\d+)?"

POSITIONAL_FEATURES = (
    [f"{i}_binary" for i in range(2, 7)]
    + [f"Molmasse_{i}" for i in range(2, 7)]
    + [f"VdW_{i}" for i in range(2, 7)]
    + [f"BV_{i}" for i in range(2, 7)]
)

CORE_FEATURES = [
    "Molecular Weight (g/mol)",
    "Rotatable Bond Count",
    "TPSA",
    "Dipole_Magnitude_Debye",
    "B–C distance (Å)",
    "B–O distance 1 (Å)",
    "B–O distance 2 (Å)",
    "Dihedral O–B–O / C–C–C (°)",
    "HOMO Energy (eV)",
    "LUMO Energy (eV)",
    "HOMO-LUMO Gap (eV)",
    "E_neutral (Eh)",
    "E_cation (Eh)",
    "E_anion (Eh)",
    "Ionization Energy (eV)",
    "Electron Affinity (eV)",
    "Mulliken_B_Charge",
    "Loewdin_B_Charge",
    "Mayer_QA",
    "Mayer_VA",
    "Mayer_BVA",
    "Mayer_FA",
]


def distance(a, b) -> float:
    return float(np.linalg.norm(np.asarray(a) - np.asarray(b)))


def plane_normal(points: list[np.ndarray]) -> np.ndarray:
    arr = np.asarray(points, dtype=float)
    centroid = arr.mean(axis=0)
    _, _, vh = np.linalg.svd(arr - centroid)
    n = vh[-1]
    return n / np.linalg.norm(n)


def geometry_features(xyz_path: Path) -> tuple[dict, dict]:
    atoms = read_xyz(xyz_path)
    symbols = [a[0] for a in atoms]
    coords = [np.asarray(a[1:], dtype=float) for a in atoms]
    b_indices = [i for i, s in enumerate(symbols) if s == "B"]
    qc = {"Number_of_B_atoms": len(b_indices), "Primary_B_atom_index": None}
    if not b_indices:
        return {}, qc

    b = b_indices[0]
    qc["Primary_B_atom_index"] = b
    neighbors = sorted(
        [(distance(coords[b], coords[i]), i) for i in range(len(atoms)) if i != b],
        key=lambda x: x[0],
    )
    o = [i for d, i in neighbors if symbols[i] == "O" and d < 2.1][:2]
    c = [i for d, i in neighbors if symbols[i] == "C" and d < 2.1][:1]
    if len(o) < 2 or len(c) < 1:
        return {}, qc

    central_c = c[0]
    c_neighbors = sorted(
        [
            (distance(coords[central_c], coords[i]), i)
            for i in range(len(atoms))
            if i != b and i != central_c and symbols[i] == "C" and distance(coords[central_c], coords[i]) < 1.7
        ],
        key=lambda x: x[0],
    )
    angle = None
    if len(c_neighbors) >= 2:
        n1 = plane_normal([coords[o[0]], coords[o[1]], coords[b]])
        n2 = plane_normal([coords[c_neighbors[0][1]], coords[c_neighbors[1][1]], coords[central_c]])
        cos_theta = float(np.clip(np.dot(n1, n2), -1.0, 1.0))
        angle = math.degrees(math.acos(cos_theta))
        if angle > 90:
            angle = 180 - angle

    return (
        {
            "B–C distance (Å)": distance(coords[b], coords[central_c]),
            "B–O distance 1 (Å)": distance(coords[b], coords[o[0]]),
            "B–O distance 2 (Å)": distance(coords[b], coords[o[1]]),
            "Dihedral O–B–O / C–C–C (°)": angle,
        },
        qc,
    )


def last_match_float(text: str, pattern: str) -> float | None:
    matches = re.findall(pattern, text, flags=re.MULTILINE)
    return float(matches[-1]) if matches else None


def dipole_feature(text: str) -> float | None:
    return last_match_float(text, rf"Magnitude \(Debye\)\s*:\s*({FLOAT})")


def homo_lumo_features(text: str) -> dict:
    lines = text.splitlines()
    starts = [i for i, line in enumerate(lines) if "ORBITAL ENERGIES" in line]
    if not starts:
        return {}
    for start in reversed(starts):
        orbitals = []
        started = False
        for line in lines[start + 1 :]:
            if "Only the first 10 virtual orbitals" in line:
                break
            parts = line.split()
            if len(parts) == 4:
                try:
                    occ = float(parts[1])
                    ev = float(parts[3])
                    orbitals.append((occ, ev))
                    started = True
                    continue
                except ValueError:
                    pass
            if started and not line.strip():
                break
        if orbitals:
            homo = None
            lumo = None
            for occ, ev in orbitals:
                if occ > 1e-6:
                    homo = ev
                elif lumo is None:
                    lumo = ev
            if homo is not None and lumo is not None:
                return {
                    "HOMO Energy (eV)": homo,
                    "LUMO Energy (eV)": lumo,
                    "HOMO-LUMO Gap (eV)": lumo - homo,
                }
    return {}


def _last_section(lines: list[str], marker: str) -> list[str]:
    starts = [i for i, line in enumerate(lines) if marker in line]
    if not starts:
        return []
    start = starts[-1]
    block = []
    started = False
    for line in lines[start + 1 :]:
        if not line.strip():
            if started:
                break
            continue
        block.append(line)
        started = True
    return block


def charge_features(text: str, boron_index: int) -> dict:
    lines = text.splitlines()
    result = {
        "Mulliken_B_Charge": None,
        "Loewdin_B_Charge": None,
        "Mayer_QA": None,
        "Mayer_VA": None,
        "Mayer_BVA": None,
        "Mayer_FA": None,
    }

    for marker, key in [
        ("MULLIKEN ATOMIC CHARGES", "Mulliken_B_Charge"),
        ("LOEWDIN ATOMIC CHARGES", "Loewdin_B_Charge"),
    ]:
        for line in _last_section(lines, marker):
            m = re.match(rf"\s*{boron_index}\s+B\s*:\s*({FLOAT})", line)
            if m:
                result[key] = float(m.group(1))
                break

    # Mayer population analysis: retain QA, VA, BVA, and FA for the boron atom.
    starts = [i for i, line in enumerate(lines) if "ATOM       NA         ZA         QA" in line]
    if starts:
        start = starts[-1]
        for line in lines[start + 1 :]:
            if not line.strip():
                continue
            m = re.match(
                rf"\s*{boron_index}\s+B\s+{FLOAT}\s+{FLOAT}\s+({FLOAT})\s+({FLOAT})\s+({FLOAT})\s+({FLOAT})",
                line,
            )
            if m:
                result.update(
                    {
                        "Mayer_QA": float(m.group(1)),
                        "Mayer_VA": float(m.group(2)),
                        "Mayer_BVA": float(m.group(3)),
                        "Mayer_FA": float(m.group(4)),
                    }
                )
                break
    return result


def rdkit_features(smiles: str) -> dict:
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return {}
    return {
        "Molecular Weight (g/mol)": Descriptors.MolWt(mol),
        "Rotatable Bond Count": Descriptors.NumRotatableBonds(mol),
        "TPSA": rdMolDescriptors.CalcTPSA(mol),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset", required=True)
    parser.add_argument(
        "--extra-features",
        type=Path,
        help="Optional CSV/XLSX with additional precomputed descriptors. It must contain MoleculeID, Molecule, or SMILES as a merge key.",
    )
    args = parser.parse_args()

    base = dataset_dir(args.dataset)
    manifest = load_manifest(args.dataset)
    dft_out_dir = base / "04_dft_geometry"
    dft_xyz_dir = base / "05_dft_xyz"
    ip_ea_path = base / "06_vertical_ip_ea" / "vertical_ip_ea_summary.csv"
    out_dir = ensure_dir(base / "08_features")

    ip_ea = pd.read_csv(ip_ea_path) if ip_ea_path.exists() else pd.DataFrame(columns=["MoleculeID"])
    rows = []
    qc_rows = []

    for _, src in manifest.iterrows():
        mol_id = str(src["MoleculeID"])
        row = src.to_dict()
        row.update(rdkit_features(str(src["SMILES"])))

        xyz_path = dft_xyz_dir / f"{mol_id}.xyz"
        out_path = dft_out_dir / f"{mol_id}.out"
        qc = {"MoleculeID": mol_id, "DFT_XYZ_present": xyz_path.exists(), "DFT_OUT_present": out_path.exists()}

        if xyz_path.exists():
            geom, geom_qc = geometry_features(xyz_path)
            row.update(geom)
            qc.update(geom_qc)
        if out_path.exists():
            text = out_path.read_text(encoding="utf-8", errors="replace")
            row["Dipole_Magnitude_Debye"] = dipole_feature(text)
            row.update(homo_lumo_features(text))
            b_idx = qc.get("Primary_B_atom_index")
            if b_idx is not None:
                row.update(charge_features(text, int(b_idx)))

        rows.append(row)
        qc_rows.append(qc)

    result = pd.DataFrame(rows)
    if not ip_ea.empty:
        keep = [
            "MoleculeID",
            "E_neutral (Eh)",
            "E_cation (Eh)",
            "E_anion (Eh)",
            "Ionization Energy (eV)",
            "Electron Affinity (eV)",
        ]
        keep = [c for c in keep if c in ip_ea.columns]
        result = result.merge(ip_ea[keep], on="MoleculeID", how="left")

    substituent_feature_path = base / "07_substituent_features" / "substituent_features.xlsx"
    if substituent_feature_path.exists():
        substituent_features = pd.read_excel(substituent_feature_path)
        if "MoleculeID" not in substituent_features.columns:
            raise ValueError(f"Substituent feature table lacks MoleculeID: {substituent_feature_path}")
        result = result.merge(substituent_features, on="MoleculeID", how="left")

    if args.extra_features:
        extra = read_table(args.extra_features)
        merge_key = next((c for c in ["MoleculeID", "Molecule", "SMILES"] if c in extra.columns and c in result.columns), None)
        if merge_key is None:
            raise ValueError("Extra feature table needs a shared MoleculeID, Molecule, or SMILES column.")
        # Reject Fukui columns even if supplied externally.
        fukui_cols = [c for c in extra.columns if c.strip().lower() in {"fukui+", "fukui-", "fukui_plus", "fukui_minus"}]
        extra = extra.drop(columns=fukui_cols, errors="ignore")
        result = result.merge(extra, on=merge_key, how="left", suffixes=("", "_extra"))

    # Final safety: never export Fukui columns.
    result = result.drop(columns=[c for c in result.columns if c.strip().lower() in {"fukui+", "fukui-", "fukui_plus", "fukui_minus"}], errors="ignore")

    # Put core descriptors after identifiers/metadata when present.
    front = [c for c in ["MoleculeID", "Molecule", "SMILES", "CanonicalSMILES"] if c in result.columns]
    core = [c for c in POSITIONAL_FEATURES + CORE_FEATURES if c in result.columns]
    remainder = [c for c in result.columns if c not in front + core]
    result = result[front + remainder + core]

    write_table(result, out_dir / "features.xlsx")
    write_table(result, out_dir / "features.csv")
    write_table(pd.DataFrame(qc_rows), out_dir / "feature_qc.csv")

    missing = result[core].isna().sum().rename("missing_values").reset_index().rename(columns={"index": "feature"}) if core else pd.DataFrame()
    if not missing.empty:
        write_table(missing, out_dir / "feature_missingness.csv")
    print(f"Final feature table -> {out_dir / 'features.xlsx'}")


if __name__ == "__main__":
    main()
